apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pokedex.fullname" . }}
  labels:
    {{- include "pokedex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pokedex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pokedex.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{.Values.image.tag }}"
          ports:
          - containerPort: {{ .Values.container.port }}
